### ISSUE TITLE
Assemble plugin

### ISSUE THREAD

**Issue by hariadi** [assemble/generator-assemble#17]
## Install plugin
- [x] `yo assemble`

and prompt will ask and list plugin available from [assemble plugin list](http://assemble.io/plugins/).
## Create new plugin
- [x] `yo assemble:plugin <name> <path>`

File `<path>/assemble-plugin-<name>.js` will be create.

**Comment by jonschlinkert** [comment]
whoa, that's a cool idea. what do you need from me? Want me to publish a plugins page now?

**Comment by hariadi** [comment]
Yes pleaseeee. :+1:
