### ISSUE TITLE
Additional generators

### ISSUE THREAD

**Issue by doowb** [assemble/generator-assemble#28]
- @hariadi 

@jonschlinkert and I were talking about creating additional generators for things commonly created for assemble. Some of these might be specific boilerplates (documentation, blogs, etc...), or they could be for plugins and helpers.

We thought about splitting these out into different repositories instead of making them sub-generators since there are cases when I just want to create a standalone helper without the rest of the assemble stuff.

What are your thoughts and advice on this?

**Comment by hariadi** [comment]
I also think like that. That would be awesome if we have generator for boilerplate, plugins and helpers.

**Comment by jonschlinkert** [comment]
:+1:

**Comment by jonschlinkert** [comment]
Great work on this guys! thanks!

**Comment by doowb** [comment]
Thanks @hariadi for updating this. I almost forgot about the issue over here. 

FYI: the new [generator-plugin](https://github.com/assemble/generator-plugin) is specific for [assemble v0.5.0](https://github.com/assemble/assemble/tree/v0.5.0). But I don't think it'll be a problem because we want new plugins to be for the refactor.

I need to get grunt-readme setup for the generator projects themselves so we can have our normal readme instead of the boilerplate from yeoman.

Also, check out [the helper generator](https://github.com/assemble/generator-helper). You can specify which type of helper/mixin you're creating :grinning:. I'm going to create a `safename` lodash mixin that I pulled from `grunt-readme` using the generator, then use it in the generator!!!

**Comment by jonschlinkert** [comment]
Should we put a disclaimer on the plugin generator so no one tries to use it before 0.5.0 is released? Looks great btw!!!

**Comment by doowb** [comment]
I think so. Thanks.
