### ISSUE TITLE
Fatal error straight away

### ISSUE THREAD

**Issue by Amparose** [assemble/generator-assemble#35]
I'm getting an error at the end of Yo and same error after a `grunt build`.

``` bash
Running "assemble:pages" (assemble) task
Fatal error: Cannot read property 'dest' of undefined
```

`grunt connect` also doesn't work - no pages are being built/shown. Can't find any "dest" in the Gruntfile.js. Bit new to all this CLI automation stuff so sorry if I'm missing the magical button somewhere.

**Comment by hariadi** [comment]
Cannot reproduce this error. 

``` shell
grunt
grunt build
grunt connect
grunt server
```

all working fine

Default [Gruntfile.js](https://github.com/assemble/generator-assemble/blob/master/app/templates/Gruntfile.js#L27) template use "dist"

**Comment by jonschlinkert** [comment]
@Amparose  perhaps try clearing your npm cache and re-installing. I don't get the error either

**Comment by Amparose** [comment]
Hmm, I still get it after clearing npm cache and doing yo assemble again. Tried other assemble generators and boilerplates and none have this issue. Anything else I could try?

**Comment by doowb** [comment]
@Amparose could you post your repository?

**Comment by stuartellis** [comment]
FWIW, I have the same issue - reinstalling global and local NPM packages didn't help. This is with Node 0.10.25 on OS X Mavericks, installed with Homebrew.

Repository: https://github.com/stuartellis/www-stuartellis-eu

**Comment by hariadi** [comment]
Can you disable `assemble-contrib-sitemap` plugin for now by removing from the plugins list

``` js
assemble: {
      pages: {
        options: {
          ...
          plugins: ['assemble-contrib-anchors','assemble-contrib-permalinks','assemble-contrib-toc','assemble-markdown-data','assemble-related-pages'],
        },
        files: {
          '<%= config.dist %>/': ['<%= config.src %>/templates/pages/*.hbs']
        }
      }
    },
```

I think this error cause by `assemble-contrib-sitemap` plugin. I'm looking for it.

**Comment by stuartellis** [comment]
Thanks - the project does now build with assemble-contrib-sitemap disabled.

**Comment by Amparose** [comment]
@doowb this error happens by just going `yo assemble` so no repo to post. @hariadi & @stuartellis removing `assemble-contrib-sitemap` also removes the error for me.

**Comment by hariadi** [comment]
Doing `npm install` again should fix  and reinstall `assemble-contrib-sitemap` to new version (v0.1.9)

Thank you guys!

**Comment by stuartellis** [comment]
Just to confirm that it works for me with 0.1.9 - thank you for the quick response, @hariadi.
