### ISSUE TITLE
Project generating in wrong folder

### ISSUE THREAD

**Issue by doowb** [assemble/generator-assemble#42]
I'm not sure if this is an issue with this generator or with yeoman.

Steps:
- `doowb$ mkdir sandbox && cd sandbox`
- `doowb$ mkdir blog` - **_Oops, I forgot to cd into `blog`_**
- `doowb$ yo assemble`
  - prompt says name of project is `sandbox` and I realize I'm in the wrong folder
  - `ctrl+c` - canceling yeoman
- `doowb$ cd blog`
- `doowb$ yo assemble`
  - prompt says name of project is `sandbox` - **_That's strange, I'll change it to `blog`_**
  - prompt only asks for plugins and skips the user name and description questions
  - npm install and grunt run
- `doowb$ ls -la` - empty directory - **_That's weird I saw assemble run._**
- `doowb$ cd .. && ls -la` - **_That's where all the files went!_**

It looks like the `.yo-rc.json` is generated with defaults up front so if I cancel the generator and go into a sub-directory, it looks for the first `.yo-rc.json` it can find in any parent directories causing it to use the incorrect information.

Like I said, I'm not sure if this is because of how yeoman `this.config` works or if it can be avoided in this generator.

**Comment by hariadi** [comment]
Great find @doowb :+1:

**Comment by doowb** [comment]
I'm trying to get used to snagit for making videos so [I made one of this issue](http://goo.gl/nezLia) (the font quality is horrible, but it gets the point across for now)

**Comment by Melindrea** [comment]
Hah! This just bit me, thanks!

**Comment by hariadi** [comment]
This is issue with yeoman. I tried with other generator that use .yo-rc.json and none of them work when generating files in sub folder.

Do we need mention this issue on README? Example:

---

_Do not initialize your project in a sub folder next to `.yo-rc.json` because your files will land here and not in your subfolder from where you are initializing project._

**Comment by jonschlinkert** [comment]
probably a good idea, thanks for looking into @hariadi
