### ISSUE TITLE
Troubles executing assemble task

### ISSUE THREAD

**Issue by cdesiles** [assemble/generator-assemble#47]
Hey there,
this evening I was trying to use **yeoman** with the **generator-assemble**, thank you first for making this happen !

Nevertheless I'm experiencing some troubles while targeting the `grunt server` task:

``` bash
~/demo> yo assemble
(lot of stuff here, npm install is fine)
~/demo> grunt server
Running "clean:0" (clean) task
Cleaning dist/sitemap.xml...OK

Running "assemble:pages" (assemble) task
(take forever, nothing happen)
```

Did I made a mistake? Should I change any file to run this out?
Thank you,

Jk.

**Comment by cdesiles** [comment]
Update : it works if not using assemble plugins (I checked them all first)

**Comment by hariadi** [comment]
Can you update the generator and test with latest? Re-open if you still has issues.

**Comment by pburtchaell** [comment]
I have been having this issue with Assemble as well —build works without plugins; build stops with plugins. I don't think it is directly related to just this generator.

**Comment by jonschlinkert** [comment]
No, it was fixed in assemble @pburtchaell https://github.com/assemble/assemble/pull/533. sorry about that

**Comment by pburtchaell** [comment]
Sweet. No problem!

**Comment by narayanpai** [comment]
i'm facing the same issue. After removing the plugins, things started working fine
