### ISSUE TITLE
Building a sample project created with generator-assemble hangs

### ISSUE THREAD

**Issue by evil-shrike** [assemble/generator-assemble#52]
- install generator-assemble globally: 'npm install generator-assemble -g'
- run the generator to create a sample project: 'yo generator-assemble'
- choose all available plugins in generator's prompt 
- after generator finishes run build: 'grunt'
- build hangs 

Actually build hangs on 'assemble-contrib-anchors' plugin. If we remove it then build succeded.

node 0.10.26
Windows 7 x64

**Comment by doowb** [comment]
Sounds like this is an issue from when we were trying to upgrade plugins/middleware to a newer version of assemble that wasn't released yet.

Try changing the version in the `package.json` from `assemble-contrib-anchors: '*'` to `assemble-contrib-anchors: '~0.1.0'` and re-run `npm i`. You might have to clear your cache `npm cache clear` first.

**Comment by IanMercer** [comment]
Removing all the contrib versions and replacing them with the middleware versions appears to work:

```
    "assemble-middleware-anchors": "^0.2.4",
    "assemble-middleware-permalinks": "^0.5.2",
    "assemble-middleware-sitemap": "^0.2.5",
    "assemble-middleware-toc": "^0.2.3",
```
