### ISSUE TITLE
Grunt doesn't seem to watch src/assets/theme.css?

### ISSUE THREAD

**Issue by smutek** [assemble/generator-assemble#56]
Hi there, 

I'm just trying your generator out and I'm noticing that Grunt doesn't seem to be watching src/assets/theme.css

For example, if I edit src/pages/index.hbs and save, my browser updates as I would expect it to. If I then change src/assets/theme.css the change doesn't take effect.

On the other hand, if I edit dist/assets/css/theme.css - for example, say I change the body background to blue, grunt see's the change and updates my page. 

I thought that I was supposed to not edit files in dist - since they are the compiled files to be used for distribution. 

Is this the intended behavior or am I doing something wrong?

Running yo assemble with the default plugins, then grunt server

Thanks for your great work!

**Comment by frankstallone** [comment]
I am diagnosing this same issue. It will compile on grunt server but any changes and the grunt watch task doesn't seem to notice. This is odd since the grunt watch list has CSS in the assets folder on watch. Line 42 of the Gruntfile.js:

'<%= config.dist %>/assets/{,_/}_.css',

Judging by the lack of community on this project it appears we are on our own @smutek. I'll let you know what I come up with.

**Comment by smutek** [comment]
Thanks @frankstallone - I'm glad to know that this isn't just me. I was beginning to think that I was just missing out on something really obvious.

**Comment by doowb** [comment]
In this generator, assemble doesn't build any of the assets, so it's only setup to watch the source content and templates. I think there was an assumption that you would add a css preprocessor like less or sass to build the css and drop them into `dist/assets/css` so the livereload is setup to watch those files and reload your browser.

You should add a new watch task for the assets to run the `copy:theme` task when they change

``` js
      theme: {
        files: ['<%= config.src %>/assets/{,*/}*.*'],
        tasks: ['copy:theme']
      }
```

**Comment by frankstallone** [comment]
Assumptions should require documentation... Or at least I didn't find any documentation mentioning that assumption. Thank you @doowb I figured it was something simple I was missing. Much appreciated!

**Comment by smutek** [comment]
Thanks as well, @doowb for the clarification. Also thanks @frankstallone for the bump!

**Comment by jonschlinkert** [comment]
> Or at least I didn't find any documentation mentioning that assumption.

it's not really an assemble convention per se, the gruntfile just follows grunt conventions

**Comment by frankstallone** [comment]
@jonschlinkert it's not an Assemble conversation at all. It's a Yeoman Assemble Generator conversation. In other words IMHO if you are going to create a Yeoman generator you should create some documentation about assumptions. @jonschlinkert you may not have created it, but you did want to move it under the official Assemble github. =)
