### ISSUE TITLE
Content block

### ISSUE THREAD

**Issue by brunowego** [assemble/generator-assemble#58]
I try add at top a block call in layout.hbs:

``` hbs
{{#block 'top'}}{{/block}}
```

And in bottom another block call in layout.hbs:

``` hbs
{{#block 'bottom'}}{{/block}}
```

In my pages:

``` hbs
{{#content 'top'}}
<!-- build:css(.) /styles/vendor/plyr.css -->
<link rel="stylesheet" href="/bower_components/plyr/dist/css/plyr.css">
<!-- endbuild -->
{{/content}}
```

``` hbs
{{#content 'bottom'}}
<!-- build:js(.) /scripts/vendor/plyr.js -->
<script src="/bower_components/plyr/dist/js/plyr.js"></script>
<script src="/bower_components/plyr/dist/js/docs.js"></script>
<!-- endbuild -->
{{/content}}
```

But not work, only call the first block. Have any idea? Thanks.

**Comment by jonschlinkert** [comment]
before I answer, would you mind recreating on assemble so other users will find the info when they search issues in the future? https://github.com/assemble/assemble/issues/new

**Comment by brunowego** [comment]
Done https://github.com/assemble/assemble/issues/652

Thanks @jonschlinkert

**Comment by jonschlinkert** [comment]
thanks!
