### ISSUE TITLE
Generate base on Assemble support engine

### ISSUE THREAD

**Issue by hariadi** [assemble/generator-assemble#9]
Engine
- handlebarjs (default)
- swig

Or [Consolidate.js](https://github.com/visionmedia/consolidate.js)!

**Comment by hariadi** [comment]
assemble/boilerplates#10
assemble/boilerplates#11

**Comment by hariadi** [comment]
Command:

``` shell
yo assemble:boilerplate [-b] <boilerplate>
```

**Comment by jonschlinkert** [comment]
It's completely up to you, but would it be better to create a different generator for swig? the templates would be completely different. or is this something that you already had planned out?

**Comment by hariadi** [comment]
For yeoman generator, yes. Better use one generator and generate boilerplate base on user choice. So user don't need to install multiple generator.

Maybe we can start with different generator for different engine, then combine to one generator?

Let me know what you think.

**Comment by jonschlinkert** [comment]
I'm not as familiar with yeoman as you are, so I'll follow your lead. In general, I agree that it's better to make things easier for users, so your suggestion of basing the result on user choice sounds like the way to go.

**Comment by jonschlinkert** [comment]
The plan is to internalize the template engines in 0.5.0, so users won't have to choose an engine this way. I think this will help us focus on boilerplates with this. Agreed?

**Comment by hariadi** [comment]
>  ..focus on boilerplates..

Agreed.

**Comment by jonschlinkert** [comment]
:+1:
